version: "3.8"

services:
  node1:
    image: image-for-blockchain:1.0
    container_name: node1
    hostname: node1
    networks:
      - blockchain
    command: "8080"

  node2:
    image: image-for-blockchain:1.0
    container_name: node2
    hostname: node2
    networks:
      - blockchain
    command: "8081"

  node3:
    image: image-for-blockchain:1.0
    container_name: node3
    hostname: node3
    networks:
      - blockchain
    command: "8082"

networks:
  blockchain: